In [1]:
!pip install faker

Collecting faker
  Downloading faker-40.36.0-py3-none-any.whl.metadata (16 kB)
Downloading faker-40.36.0-py3-none-any.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 40.9 MB/s eta 0:00:00
Installing collected packages: faker
Successfully installed faker-40.36.0

In [2]:
import pandas as pd
import numpy as np
from faker import Faker
import random

# Set seed for reproducibility
random.seed(42)
np.random.seed(42)

fake = Faker()

In [4]:
# Number of transactions
NUM_TRANSACTIONS = 10000

In [5]:
countries = [
    "UAE",
    "Saudi Arabia",
    "Kuwait",
    "Qatar"
]

merchants = [
    "Noon",
    "Amazon UAE",
    "Jarir",
    "Namshi",
    "Extra",
    "Carrefour",
    "IKEA",
    "Centrepoint",
    "Sharaf DG",
    "Virgin Megastore"
]

categories = [
    "Electronics",
    "Fashion",
    "Home",
    "Beauty",
    "Travel"
]

payment_status = [
    "Paid",
    "Late",
    "Default"
]

installments = [2,3,4,6]

In [6]:
transactions = []

for i in range(NUM_TRANSACTIONS):

    transactions.append({

        "Transaction_ID": i + 1,

        "Customer_ID": random.randint(100000,999999),

        "Customer_Name": fake.name(),

        "Email": fake.email(),

        "Phone": fake.phone_number(),

        "Country": random.choice(countries),

        "Merchant": random.choice(merchants),

        "Category": random.choice(categories),

        "Order_Value": round(random.uniform(50,5000),2),

        "Installments": random.choice(installments),

        "Payment_Status": random.choices(
            payment_status,
            weights=[80,15,5]
        )[0],

        "Days_Late": random.randint(0,45),

        "Credit_Score": random.randint(550,850),

        "Monthly_Income": random.randint(3000,30000),

        "Age": random.randint(18,60),

        "Order_Date": fake.date_between(
            start_date="-2y",
            end_date="today"
        )

    })

In [7]:
df = pd.DataFrame(transactions)

In [8]:
df.head()

,Transaction_ID,Customer_ID,Customer_Name,Email,Phone,Country,Merchant,Category,Order_Value,Installments,Payment_Status,Days_Late,Credit_Score,Monthly_Income,Age,Order_Date
0,1,770487,Brandon Haynes,danielchase@example.org,339.319.6875,UAE,Noon,Home,1262.21,3,Paid,43,829,5848,55,2024-12-22
1,2,542417,Carolyn Vargas,kenneth97@example.com,+1-558-767-8671x5616,UAE,Noon,Electronics,1132.26,2,Paid,45,829,16746,32,2026-01-28
2,3,571029,Joy Martinez,ejohnson@example.org,470-731-6696x2513,Kuwait,Noon,Fashion,3505.79,4,Paid,13,722,6349,23,2025-07-25
3,4,498382,Mary Montgomery,nicholas97@example.org,7435582889,UAE,Carrefour,Home,3038.44,2,Paid,34,613,15403,23,2025-11-07
4,5,678856,Casey Johnson,strongalisha@example.net,+1-705-452-3242x33229,Kuwait,Virgin Megastore,Home,2907.89,2,Paid,14,698,5614,32,2024-11-24

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Transaction_ID  10000 non-null  int64
 1   Customer_ID     10000 non-null  int64
 2   Customer_Name   10000 non-null  object
 3   Email           10000 non-null  object
 4   Phone           10000 non-null  object
 5   Country         10000 non-null  object
 6   Merchant        10000 non-null  object
 7   Category        10000 non-null  object
 8   Order_Value     10000 non-null  float64
 9   Installments    10000 non-null  int64
 10  Payment_Status  10000 non-null  object
 11  Days_Late       10000 non-null  int64
 12  Credit_Score    10000 non-null  int64
 13  Monthly_Income  10000 non-null  int64
 14  Age             10000 non-null  int64
 15  Order_Date      10000 non-null  object
dtypes: float64(1), int64(7), object(8)
memory usage: 1.2+ MB

In [10]:
df.describe()

,Transaction_ID,Customer_ID,Order_Value,Installments,Days_Late,Credit_Score,Monthly_Income,Age
count,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,5000.50000,550650.453200,2535.167508,3.741700,22.713800,700.697200,16430.713500,39.082900
std,2886.89568,260099.640292,1436.429114,1.486002,13.173437,86.802264,7840.706925,12.380701
min,1.00000,100009.000000,50.030000,2.000000,0.000000,550.000000,3008.000000,18.000000
25%,2500.75000,323616.250000,1292.662500,2.000000,11.000000,625.000000,9573.250000,28.000000
50%,5000.50000,552498.000000,2516.295000,3.000000,23.000000,701.000000,16386.500000,39.000000
75%,7500.25000,780195.750000,3784.580000,6.000000,34.000000,777.000000,23220.250000,50.000000
max,10000.00000,999969.000000,4999.080000,6.000000,45.000000,850.000000,29997.000000,60.000000

In [11]:
df.loc[df.sample(150).index, "Monthly_Income"] = np.nan

df.loc[df.sample(120).index, "Credit_Score"] = np.nan

In [12]:
duplicates = df.sample(75)

df = pd.concat([df, duplicates], ignore_index=True)

In [13]:
df.loc[df.sample(40).index, "Order_Value"] = -100

In [14]:
df.loc[df.sample(20).index, "Merchant"] = "Nooon"

df.loc[df.sample(20).index, "Merchant"] = "Amazon"

df.loc[df.sample(20).index, "Merchant"] = "Jarirr"

In [15]:
print("Shape:", df.shape)

print("\nMissing Values")
print(df.isnull().sum())

print("\nDuplicate Rows")
print(df.duplicated().sum())

Shape: (10075, 16)

Missing Values
Transaction_ID      0
Customer_ID         0
Customer_Name       0
Email               0
Phone               0
Country             0
Merchant            0
Category            0
Order_Value         0
Installments        0
Payment_Status      0
Days_Late           0
Credit_Score      120
Monthly_Income    151
Age                 0
Order_Date          0
dtype: int64

Duplicate Rows
73

In [16]:
df.to_csv("raw_bnpl_data.csv", index=False)

print("Raw dataset saved successfully!")

Raw dataset saved successfully!

In [17]:
import pandas as pd
import numpy as np

df = pd.read_csv("raw_bnpl_data.csv")

print(df.shape)
df.head()

(10075, 16)

,Transaction_ID,Customer_ID,Customer_Name,Email,Phone,Country,Merchant,Category,Order_Value,Installments,Payment_Status,Days_Late,Credit_Score,Monthly_Income,Age,Order_Date
0,1,770487,Brandon Haynes,danielchase@example.org,339.319.6875,UAE,Noon,Home,1262.21,3,Paid,43,829.0,5848.0,55,2024-12-22
1,2,542417,Carolyn Vargas,kenneth97@example.com,+1-558-767-8671x5616,UAE,Noon,Electronics,1132.26,2,Paid,45,829.0,16746.0,32,2026-01-28
2,3,571029,Joy Martinez,ejohnson@example.org,470-731-6696x2513,Kuwait,Noon,Fashion,3505.79,4,Paid,13,722.0,6349.0,23,2025-07-25
3,4,498382,Mary Montgomery,nicholas97@example.org,7435582889,UAE,Carrefour,Home,3038.44,2,Paid,34,613.0,15403.0,23,2025-11-07
4,5,678856,Casey Johnson,strongalisha@example.net,+1-705-452-3242x33229,Kuwait,Virgin Megastore,Home,2907.89,2,Paid,14,698.0,5614.0,32,2024-11-24

In [18]:
print("Data Types")
print(df.dtypes)

print("\nMissing Values")
print(df.isnull().sum())

print("\nDuplicate Rows")
print(df.duplicated().sum())

Data Types
Transaction_ID      int64
Customer_ID         int64
Customer_Name      object
Email              object
Phone              object
Country            object
Merchant           object
Category           object
Order_Value       float64
Installments        int64
Payment_Status     object
Days_Late           int64
Credit_Score      float64
Monthly_Income    float64
Age                 int64
Order_Date         object
dtype: object

Missing Values
Transaction_ID      0
Customer_ID         0
Customer_Name       0
Email               0
Phone               0
Country             0
Merchant            0
Category            0
Order_Value         0
Installments        0
Payment_Status      0
Days_Late           0
Credit_Score      120
Monthly_Income    151
Age                 0
Order_Date          0
dtype: int64

Duplicate Rows
73

In [19]:
df = df.drop_duplicates()

print("New Shape:", df.shape)

New Shape: (10002, 16)

In [20]:
df["Monthly_Income"] = df["Monthly_Income"].fillna(df["Monthly_Income"].median())

df["Credit_Score"] = df["Credit_Score"].fillna(df["Credit_Score"].median())

In [21]:
df.isnull().sum()

Transaction_ID    0
Customer_ID       0
Customer_Name     0
Email             0
Phone             0
Country           0
Merchant          0
Category          0
Order_Value       0
Installments      0
Payment_Status    0
Days_Late         0
Credit_Score      0
Monthly_Income    0
Age               0
Order_Date        0
dtype: int64

In [22]:
df[df["Order_Value"] < 0]

,Transaction_ID,Customer_ID,Customer_Name,Email,Phone,Country,Merchant,Category,Order_Value,Installments,Payment_Status,Days_Late,Credit_Score,Monthly_Income,Age,Order_Date
94,95,555052,Lauren Smith,mrodriguez@example.com,(739)429-8179x17529,UAE,Amazon UAE,Beauty,-100.0,4,Late,2,716.0,29088.0,21,2026-03-21
150,151,335445,Julia Williams,hpittman@example.com,361-258-8674,UAE,Carrefour,Electronics,-100.0,4,Paid,8,569.0,12400.0,48,2026-02-19
333,334,511987,Jo Martinez,kmadden@example.com,443.448.2102x7449,Qatar,Jarir,Electronics,-100.0,6,Paid,42,795.0,9542.0,24,2026-01-30
965,966,449935,Patty Thomas,anitabradley@example.com,+1-934-509-2406x3200,UAE,Carrefour,Electronics,-100.0,3,Paid,33,721.0,22648.0,29,2025-03-02
1005,1006,571155,Kimberly Ramos,adamadams@example.com,(479)821-0747x670,UAE,Noon,Fashion,-100.0,3,Paid,34,635.0,22691.0,42,2025-08-15
1145,1146,108357,Adrian Jones,richard89@example.org,929-386-6942x49503,Saudi Arabia,Jarir,Travel,-100.0,3,Paid,16,790.0,7962.0,49,2025-05-06
1451,1452,244327,Olivia Thompson,robinsonmichael@example.com,(833)267-4292x2110,Kuwait,Carrefour,Beauty,-100.0,3,Late,21,809.0,23482.0,27,2025-05-02
1481,1482,894210,William Glenn,stephen95@example.net,001-409-971-3562x164,Saudi Arabia,Centrepoint,Home,-100.0,6,Default,34,814.0,23197.0,58,2025-06-06
1834,1835,312129,Daniel White,sabrinanelson@example.org,001-840-988-9612,Kuwait,Sharaf DG,Fashion,-100.0,6,Paid,38,785.0,28719.0,18,2026-05-16
1911,1912,492022,Briana Macias,alicia88@example.com,+1-819-381-8077x3303,Kuwait,Carrefour,Beauty,-100.0,6,Late,36,687.0,19363.0,39,2025-06-26
3028,3029,177060,Amanda James,kingkimberly@example.com,528.380.0186,UAE,Centrepoint,Fashion,-100.0,6,Paid,45,820.0,16949.0,27,2026-04-15
3192,3193,295563,Steven Juarez,william41@example.com,498-282-5704x80626,Saudi Arabia,Sharaf DG,Home,-100.0,3,Paid,35,722.0,27336.0,35,2024-08-28
3219,3220,230751,Mrs. Jessica Finley,nancylopez@example.net,811-510-8391x5873,Saudi Arabia,Noon,Fashion,-100.0,4,Paid,40,783.0,26297.0,48,2025-07-06
3651,3652,657608,Richard Campbell,danny49@example.com,+1-678-211-4651x5689,Kuwait,Carrefour,Travel,-100.0,4,Paid,18,732.0,8029.0,54,2025-03-17
4029,4030,803411,Morgan Rivers,marquezcody@example.com,001-360-958-1928x832,Saudi Arabia,Virgin Megastore,Beauty,-100.0,3,Paid,40,633.0,28081.0,56,2025-11-08
4122,4123,204122,Tony Hamilton,qsmith@example.com,(482)447-7159x071,Saudi Arabia,Carrefour,Electronics,-100.0,3,Paid,33,698.0,4086.0,22,2025-08-24
4359,4360,460040,Rachel Hicks,vthomas@example.com,001-959-440-0086x6773,Kuwait,Virgin Megastore,Travel,-100.0,4,Paid,11,580.0,11530.0,22,2025-07-24
4600,4601,366522,Brittany Young,mscott@example.com,(391)455-0062x940,UAE,Noon,Travel,-100.0,3,Paid,22,574.0,18472.0,53,2025-01-01
4995,4996,433265,Kimberly Boyer,kevinchen@example.com,258-911-2097x9521,Qatar,Namshi,Home,-100.0,2,Paid,4,583.0,15475.0,32,2025-09-05
5153,5154,160128,Robert Perkins,dmoyer@example.net,001-467-562-1027x711,Saudi Arabia,IKEA,Beauty,-100.0,2,Paid,14,628.0,26237.0,51,2026-01-28
5226,5227,252143,Adam Anderson,fgeorge@example.org,769-386-0256x399,Qatar,Amazon UAE,Travel,-100.0,3,Paid,6,823.0,18659.0,56,2025-04-29
5818,5819,189539,Thomas Nelson,daniellelewis@example.org,001-279-667-3777,UAE,Noon,Electronics,-100.0,6,Paid,7,815.0,8127.0,44,2026-01-07
6008,6009,965465,Nathan Fields,thomascharlene@example.com,001-727-770-4355x2863,Saudi Arabia,Carrefour,Travel,-100.0,4,Late,1,773.0,8699.0,47,2025-04-15
6735,6736,189277,Jason Kim,caitlin65@example.org,235-567-1953,Qatar,Centrepoint,Fashion,-100.0,3,Paid,33,650.0,16900.0,32,2025-12-11
6929,6930,818849,Gerald Graham,alexander77@example.org,8278400683,Kuwait,Carrefour,Travel,-100.0,6,Paid,38,742.0,10398.0,51,2026-05-29
6933,6934,324631,Brandon Roy,nclark@example.com,001-690-295-8071x83802,Qatar,Sharaf DG,Fashion,-100.0,4,Paid,45,705.0,15993.0,34,2024-08-05
7215,7216,610083,Dylan Mcclure,jwilliams@example.net,(568)740-8062,Saudi Arabia,IKEA,Travel,-100.0,3,Paid,41,708.0,18211.0,44,2024-09-12
7948,7949,519217,Brian Chavez,lmorrison@example.net,232-339-1048x181,Kuwait,Sharaf DG,Beauty,-100.0,2,Paid,14,761.0,12059.0,52,2026-05-29
8008,8009,890320,Anthony Patton,marierogers@example.org,8523685313,Saudi Arabia,Namshi,Home,-100.0,6,Paid,32,830.0,26922.0,32,2025-11-16
8274,8275,587006,Kristin Scott,jennifertucker@example.org,(337)438-0573,Kuwait,Namshi,Electronics,-100.0,4,Paid,3,719.0,14637.0,46,2026-05-30
8288,8289,864553,Dawn Mcdowell,christopherjordan@example.org,8799809663,Kuwait,Extra,Electronics,-100.0,6,Paid,16,627.0,21326.0,29,2026-05-22
8333,8334,633152,Katherine Alvarez,brianna48@example.org,(505)693-6041,Qatar,Sharaf DG,Home,-100.0,3,Paid,19,565.0,16647.0,54,2025-08-28
8589,8590,870478,Terry Taylor,mrobertson@example.org,464-440-4721x367,Kuwait,Amazon UAE,Home,-100.0,6,Paid,28,815.0,3718.0,50,2025-04-12
8679,8680,907249,Richard Cooper,ronald64@example.org,(523)698-8300x790,Kuwait,Amazon UAE,Beauty,-100.0,6,Paid,18,618.0,25104.0,32,2025-05-03
9041,9042,465998,Cheyenne Miller,bthompson@example.net,851.325.4093,Saudi Arabia,Centrepoint,Home,-100.0,6,Paid,27,637.0,24884.0,24,2026-01-31
9403,9404,432643,Ashley Brady,jose02@example.net,(639)259-8735,UAE,Centrepoint,Beauty,-100.0,6,Paid,36,826.0,6468.0,40,2025-02-07
9700,9701,816545,Debra Ramos,estevens@example.com,+1-654-840-8738x51736,Kuwait,Amazon UAE,Fashion,-100.0,6,Paid,44,671.0,3742.0,45,2026-07-14
9902,9903,409325,James Holmes,patricia55@example.org,001-426-236-4707x37174,Saudi Arabia,Carrefour,Electronics,-100.0,3,Paid,27,610.0,17387.0,38,2025-05-19
9948,9949,585525,Mark Hobbs,clong@example.com,386-680-3744x8465,Qatar,Noon,Fashion,-100.0,4,Paid,17,698.0,17080.0,41,2024-08-16
10045,1951,177797,Mariah Crawford,courtneywoodard@example.com,746-440-2275x5002,Saudi Arabia,IKEA,Beauty,-100.0,3,Paid,38,644.0,7320.0,46,2026-02-21

In [23]:
median_order = df[df["Order_Value"] > 0]["Order_Value"].median()

df.loc[df["Order_Value"] < 0, "Order_Value"] = median_order

In [24]:
merchant_mapping = {
    "Amazon": "Amazon UAE",
    "Nooon": "Noon",
    "Jarirr": "Jarir"
}

df["Merchant"] = df["Merchant"].replace(merchant_mapping)

In [25]:
df["Merchant"].value_counts()

Merchant
Amazon UAE          1054
IKEA                1025
Noon                1023
Centrepoint         1018
Sharaf DG           1016
Jarir               1001
Extra                989
Carrefour            974
Virgin Megastore     958
Namshi               944
Name: count, dtype: int64

In [26]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"])

In [27]:
df["Order_Month"] = df["Order_Date"].dt.month_name()

In [28]:
df["Order_Year"] = df["Order_Date"].dt.year

In [29]:
df["Quarter"] = df["Order_Date"].dt.quarter

In [33]:
conditions = [
    df["Credit_Score"] >= 720,
    (df["Credit_Score"] >= 650) & (df["Credit_Score"] < 720),
    df["Credit_Score"] < 650
]

choices = [
    "Low Risk",
    "Medium Risk",
    "High Risk"
]

df["Risk_Level"] = np.select(
    conditions,
    choices,
    default="Unknown"
)

In [31]:
conditions = [
    df["Age"] <= 25,
    (df["Age"] > 25) & (df["Age"] <= 40),
    df["Age"] > 40
]

choices = [
    "18-25",
    "26-40",
    "40+"
]

df["Age_Group"] = np.select(conditions, choices)

TypeError: Choicelist and default value do not have a common dtype: The DType <class 'numpy.dtypes._PyLongDType'> could not be promoted by <class 'numpy.dtypes.StrDType'>. This means that no common DType exists for the given inputs. For example they cannot be stored in a single array unless the dtype is `object`. The full list of DTypes is: (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes._PyLongDType'>)

In [32]:
conditions = [
    df["Age"] <= 25,
    (df["Age"] > 25) & (df["Age"] <= 40),
    df["Age"] > 40
]

choices = [
    "18-25",
    "26-40",
    "40+"
]

df["Age_Group"] = np.select(
    conditions,
    choices,
    default="Unknown"
)

In [34]:
conditions = [
    df["Monthly_Income"] < 8000,
    (df["Monthly_Income"] >= 8000) & (df["Monthly_Income"] < 15000),
    df["Monthly_Income"] >= 15000
]

choices = [
    "Low Income",
    "Middle Income",
    "High Income"
]

df["Income_Band"] = np.select(
    conditions,
    choices,
    default="Unknown"
)

In [35]:
conditions = [
    df["Order_Value"] >= 3000,
    (df["Order_Value"] >= 1000) & (df["Order_Value"] < 3000),
    df["Order_Value"] < 1000
]

choices = [
    "Premium",
    "Regular",
    "Budget"
]

df["Customer_Segment"] = np.select(
    conditions,
    choices,
    default="Unknown"
)

In [36]:
print(df.info())

print("\nMissing Values")
print(df.isnull().sum())

print("\nDuplicate Rows")
print(df.duplicated().sum())

df.head()

<class 'pandas.core.frame.DataFrame'>
Index: 10002 entries, 0 to 10074
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction_ID    10002 non-null  int64
 1   Customer_ID       10002 non-null  int64
 2   Customer_Name     10002 non-null  object
 3   Email             10002 non-null  object
 4   Phone             10002 non-null  object
 5   Country           10002 non-null  object
 6   Merchant          10002 non-null  object
 7   Category          10002 non-null  object
 8   Order_Value       10002 non-null  float64
 9   Installments      10002 non-null  int64
 10  Payment_Status    10002 non-null  object
 11  Days_Late         10002 non-null  int64
 12  Credit_Score      10002 non-null  float64
 13  Monthly_Income    10002 non-null  float64
 14  Age               10002 non-null  int64
 15  Order_Date        10002 non-null  datetime64[ns]
 16  Order_Month       10002 non-null  object
 17  Order_Year        10002 non-null  int32
 18  Quarter           10002 non-null  int32
 19  Risk_Level        10002 non-null  object
 20  Age_Group         10002 non-null  object
 21  Income_Band       10002 non-null  object
 22  Customer_Segment  10002 non-null  object
dtypes: datetime64[ns](1), float64(3), int32(2), int64(5), object(12)
memory usage: 1.8+ MB
None

Missing Values
Transaction_ID      0
Customer_ID         0
Customer_Name       0
Email               0
Phone               0
Country             0
Merchant            0
Category            0
Order_Value         0
Installments        0
Payment_Status      0
Days_Late           0
Credit_Score        0
Monthly_Income      0
Age                 0
Order_Date          0
Order_Month         0
Order_Year          0
Quarter             0
Risk_Level          0
Age_Group           0
Income_Band         0
Customer_Segment    0
dtype: int64

Duplicate Rows
0

,Transaction_ID,Customer_ID,Customer_Name,Email,Phone,Country,Merchant,Category,Order_Value,Installments,...,Monthly_Income,Age,Order_Date,Order_Month,Order_Year,Quarter,Risk_Level,Age_Group,Income_Band,Customer_Segment
0,1,770487,Brandon Haynes,danielchase@example.org,339.319.6875,UAE,Noon,Home,1262.21,3,...,5848.0,55,2024-12-22,December,2024,4,Low Risk,40+,Low Income,Regular
1,2,542417,Carolyn Vargas,kenneth97@example.com,+1-558-767-8671x5616,UAE,Noon,Electronics,1132.26,2,...,16746.0,32,2026-01-28,January,2026,1,Low Risk,26-40,High Income,Regular
2,3,571029,Joy Martinez,ejohnson@example.org,470-731-6696x2513,Kuwait,Noon,Fashion,3505.79,4,...,6349.0,23,2025-07-25,July,2025,3,Low Risk,18-25,Low Income,Premium
3,4,498382,Mary Montgomery,nicholas97@example.org,7435582889,UAE,Carrefour,Home,3038.44,2,...,15403.0,23,2025-11-07,November,2025,4,High Risk,18-25,High Income,Premium
4,5,678856,Casey Johnson,strongalisha@example.net,+1-705-452-3242x33229,Kuwait,Virgin Megastore,Home,2907.89,2,...,5614.0,32,2024-11-24,November,2024,4,Medium Risk,26-40,Low Income,Regular

In [37]:
df.to_csv("clean_bnpl_data.csv", index=False)

print("Clean dataset exported successfully!")

Clean dataset exported successfully!